# Generated by Django 2.2.5 on 2019-09-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190915_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
    ]
