# Generated by Django 2.2.5 on 2019-09-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
