# Generated by Django 2.2.5 on 2019-09-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20190920_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_modifieds',
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
